sudo: required
services:
  - docker

before_install:
  - docker build -t priyojit/react-docker-demo -f Dockerfile.dev .

script:
  - docker run -e CI=true priyojit/react-docker-demo npm run test -- --coverage
